### ISSUE TITLE
~,! are not valid character for filenames under Linux

### ISSUE THREAD

**Issue by kenkangxgwe** [xiaoxinghu/dotfiles#1]
Come from the blog. May be you should mention that it only works for Mac. But I like the idea of notations.

**Comment by xiaoxinghu** [comment]
Thanks for the feedback, but I just tried the whole thing in a ubuntu docker container, and it seems to work fine. Well, after I've fixed the shebang 7855ec1ef4ca08fe2fde22b7126f0eeb3d18254e. Can you provide more specific setup info, like Linux distro and version info etc.?

**Comment by kenkangxgwe** [comment]
Oh, it was my bad to name a new file using ~ and ! without escaping in the bash. I should have `mkdir \!foldername` instead of `mkdir !foldername`. Thanks for testing it under Linux, and sorry for bothering.
